### ISSUE TITLE
`ndn-tlv` not available on GitHub yet

### ISSUE THREAD

**Issue by JKRhb** [ndn-cluster-rs/ndn-app#1]
Hi there! :) Firstly, thank you for creating and publishing your NDN crates!

Trying to compile the example from the README, I've noticed that the `ndn-tlv` crate isn't available on GitHub yet – replacing the relative path dependencies with the versions published on crates.io leads to a number of compile errors as some definitions are not available or have changed, apparently. Would it be possible to also publish that crate here in the GitHub organization?

Have you also considered managing the different crates within a [cargo workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html), by the way? I was wondering if that could make it easier to keep the different crates and their common dependencies synchronized 🤔

**Comment by Xandaros** [comment]
Oh, my bad - I did upload it to GitHub, but apparently forgot to set it to public. (Turns out, new repos in an organisation default to private)

Indeed, the versions on crates.io or a bit older and won't be compatible. I should probably update them at some point, since changes to these crates have slowed down quite a bit now.

And yes, I do use a Cargo workspace for the repos locally. I was considering creating an overarching repo, with all the component repos as submodules, but ended up deciding against that, as working with submodules can be a hassle.
